In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("../Datasets/placement_predict_50k Dataset.csv")
df.head()

,StudentID,Gender,City,CollegeTier,Stream,Specialisation,Hostel,HistoryOfBacklogs,SGPA_Sem1,SGPA_Sem2,...,Publications,AptitudeTestScore,SoftSkillsRating,CodingTestScore,MockInterviewScore,ExtraCurricular,CGPA_Tier,PlacementStatus,IsAnomaly,Salary Package
0,1,Male,Ahmedabad,Tier2,ECE,Networking,No,No,6.02,6.54,...,0,66.7,2.2,49.4,47.8,0,Low,0,0,0.00
1,2,Female,Mumbai,Tier2,ECE,DataScience,Yes,Yes,5.84,5.12,...,0,48.2,2.4,26.7,25.8,0,Low,0,0,0.00
2,3,Male,Kolkata,Tier2,IT,DataScience,Yes,No,4.91,5.29,...,0,73.8,2.8,67.7,41.5,0,Low,1,0,3.89
3,4,Male,Jaipur,Tier1,CS,AI,No,No,7.67,8.03,...,0,69.8,2.7,66.9,48.0,0,Mid,1,0,8.37
4,5,Male,Pune,Tier2,IT,DataScience,Yes,No,8.14,8.97,...,1,73.1,2.1,71.7,61.7,1,High,1,0,18.99

In [4]:
print("Dataset shape: ", df.shape)

Dataset shape:  (50000, 32)

In [5]:
print("Columns: ")
print(df.columns.tolist())

Columns:
['StudentID', 'Gender', 'City', 'CollegeTier', 'Stream', 'Specialisation', 'Hostel', 'HistoryOfBacklogs', 'SGPA_Sem1', 'SGPA_Sem2', 'SGPA_Sem3', 'SGPA_Sem4', 'SGPA_Sem5', 'SGPA_Sem6', 'SGPA_Sem7', 'SGPA_Sem8', 'CGPA', 'AttendancePercent', 'Internships', 'Projects', 'Workshops', 'Certifications', 'Publications', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore', 'ExtraCurricular', 'CGPA_Tier', 'PlacementStatus', 'IsAnomaly', 'Salary Package']

In [6]:
print("Data types: ")
print(df.dtypes)

Data types:
StudentID               int64
Gender                    str
City                      str
CollegeTier               str
Stream                    str
Specialisation            str
Hostel                    str
HistoryOfBacklogs         str
SGPA_Sem1             float64
SGPA_Sem2             float64
SGPA_Sem3             float64
SGPA_Sem4             float64
SGPA_Sem5             float64
SGPA_Sem6             float64
SGPA_Sem7             float64
SGPA_Sem8             float64
CGPA                  float64
AttendancePercent     float64
Internships             int64
Projects                int64
Workshops             float64
Certifications          int64
Publications            int64
AptitudeTestScore     float64
SoftSkillsRating      float64
CodingTestScore       float64
MockInterviewScore    float64
ExtraCurricular         int64
CGPA_Tier                 str
PlacementStatus         int64
IsAnomaly               int64
Salary Package        float64
dtype: object

In [7]:
df.isnull()

,StudentID,Gender,City,CollegeTier,Stream,Specialisation,Hostel,HistoryOfBacklogs,SGPA_Sem1,SGPA_Sem2,...,Publications,AptitudeTestScore,SoftSkillsRating,CodingTestScore,MockInterviewScore,ExtraCurricular,CGPA_Tier,PlacementStatus,IsAnomaly,Salary Package
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
49999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

StudentID                0
Gender                   0
City                     0
CollegeTier              0
Stream                   0
Specialisation           0
Hostel                   0
HistoryOfBacklogs        0
SGPA_Sem1                0
SGPA_Sem2                0
SGPA_Sem3                0
SGPA_Sem4                0
SGPA_Sem5                0
SGPA_Sem6                0
SGPA_Sem7                0
SGPA_Sem8                0
CGPA                     0
AttendancePercent        0
Internships              0
Projects                 0
Workshops             4488
Certifications           0
Publications             0
AptitudeTestScore     4029
SoftSkillsRating      3526
CodingTestScore       2976
MockInterviewScore    4957
ExtraCurricular          0
CGPA_Tier                0
PlacementStatus          0
IsAnomaly                0
Salary Package           0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(19976)

In [10]:
X = df.drop(columns=["PlacementStatus"])
y = df["PlacementStatus"]

print("Features shape: ", X.shape)
print("Target shape: ", y.shape)

Features shape:  (50000, 31)
Target shape:  (50000,)

In [11]:
print(y.value_counts())

PlacementStatus
1    32856
0    17144
Name: count, dtype: int64

In [12]:
X = df.drop(
    columns = [
        "PlacementStatus",
        "StudentID",
        "Salary Package"
    ],
    errors="ignore"
)

y = df['PlacementStatus']

In [13]:
categorical_columns = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

print("\nNumerical columns:")
print(numerical_columns)

Categorical columns:
['Gender', 'City', 'CollegeTier', 'Stream', 'Specialisation', 'Hostel', 'HistoryOfBacklogs', 'CGPA_Tier']

Numerical columns:
['SGPA_Sem1', 'SGPA_Sem2', 'SGPA_Sem3', 'SGPA_Sem4', 'SGPA_Sem5', 'SGPA_Sem6', 'SGPA_Sem7', 'SGPA_Sem8', 'CGPA', 'AttendancePercent', 'Internships', 'Projects', 'Workshops', 'Certifications', 'Publications', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore', 'ExtraCurricular', 'IsAnomaly']

C:\Users\DELL\AppData\Local\Temp\ipykernel_15908\38333173.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(

In [16]:
y = df["PlacementStatus"]

In [17]:
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Validation samples:", X_val.shape[0])

Training samples: 40000
Validation samples: 10000

In [18]:
preprocessor = ColumnTransformer (
    transformers = [
        (
            "num",
            StandardScaler(),
            numerical_columns
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_columns
        )
    ]
)

In [19]:
X_train_processed = preprocessor.fit_transform(X_train)

X_val_processed = preprocessor.transform(X_val)

print("Processed training shape:", X_train_processed.shape)
print("Processed validation shape:", X_val_processed.shape)

Processed training shape: (40000, 53)
Processed validation shape: (10000, 53)

In [20]:
def compare_regularisation(
    X_train,
    y_train,
    X_val,
    y_val,
    C_values
):
    
    results = []

    for C in C_values:
        
        lasso_model = Pipeline([
            ("preprocessor", preprocessor),
            (
                "classifier",
                LogisticRegression(
                    penalty="l1",
                    C=C,
                    solver="liblinear",
                    max_iter=2000
                )
            )
        ])

        lasso_model.fit(X_train, y_train)

        lasso_pred = lasso_model.predict(X_val)

        lasso_accuracy = accuracy_score(
            y_val,
            lasso_pred
        )

        lasso_coefficients = (
            lasso_model
            .named_steps["classifier"]
            .coef_
        )

        lasso_nonzero = np.count_nonzero(
            lasso_coefficients
        )


        ridge_model = Pipeline([
            ("preprocessor", preprocessor),
            (
                "classifier",
                LogisticRegression(
                    penalty="l2",
                    C=C,
                    solver="liblinear",
                    max_iter=2000
                )
            )
        ])

        ridge_model.fit(X_train, y_train)

        ridge_pred = ridge_model.predict(X_val)

        ridge_accuracy = accuracy_score(
            y_val,
            ridge_pred
        )

        ridge_coefficients = (
            ridge_model
            .named_steps["classifier"]
            .coef_
        )

        ridge_nonzero = np.count_nonzero(
            ridge_coefficients
        )


        elastic_model = Pipeline([
            ("preprocessor", preprocessor),
            (
                "classifier",
                LogisticRegression(
                    penalty="elasticnet",
                    C=C,
                    solver="saga",
                    l1_ratio=0.5,
                    max_iter=5000
                )
            )
        ])

        elastic_model.fit(X_train, y_train)

        elastic_pred = elastic_model.predict(X_val)

        elastic_accuracy = accuracy_score(
            y_val,
            elastic_pred
        )



        results.append({
            "C": C,
            "Lasso_val_acc": lasso_accuracy,
            "Ridge_val_acc": ridge_accuracy,
            "ElasticNet_val_acc": elastic_accuracy,
            "Lasso_nonzero": lasso_nonzero,
            "Ridge_nonzero": ridge_nonzero
        })


    return pd.DataFrame(results)

In [21]:
C_values = [0.001, 0.01, 0.1, 1, 10, 100]
print(C_values)

[0.001, 0.01, 0.1, 1, 10, 100]

In [22]:
results = compare_regularisation(X_train, y_train, X_val, y_val, C_values)
print(results)

c:\Users\DELL\OneDrive\Desktop\ML\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\DELL\OneDrive\Desktop\ML\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [23]:
results[
    [
        "C",
        "Lasso_val_acc",
        "Ridge_val_acc",
        "ElasticNet_val_acc"
    ]
].style.format({
    "Lasso_val_acc": "{:.4f}",
    "Ridge_val_acc": "{:.4f}",
    "ElasticNet_val_acc": "{:.4f}"
})

NameError: name 'results' is not defined